import { configureStore, createSlice, PayloadAction } from "@reduxjs/toolkit";

// Define the initial state using a type
interface CounterState {
  value: number;
}

const initialState: CounterState = {
  value: 0,
};

// Create a slice
const counterSlice = createSlice({
  name: "counter",
  initialState,
  reducers: {
    increment: (state) => {
      state.value += 1;
    },
    decrement: (state) => {
      state.value -= 1;
    },
    incrementByAmount: (state, action: PayloadAction<number>) => {
      state.value += action.payload;
    },
  },
});

// Export the actions generated by createSlice
export const { increment, decrement, incrementByAmount } = counterSlice.actions;

// Create and configure the store
export const store = configureStore({
  reducer: {
    counter: counterSlice.reducer,
  },
});

// Export the type of the RootState
export type RootState = ReturnType<typeof store.getState>;

// Export the type of the AppDispatch
export type AppDispatch = typeof store.dispatch;
